<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_05_%EC%97%AC%EB%9F%AC_%ED%85%90%EC%84%9C_%ED%95%A9%EC%B9%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.zeros(2, 3)
y = torch.ones(2, 3)

In [3]:
# concatenate
cat0 = torch.cat([x, y], dim=0)
cat1 = torch.cat([x, y], dim=1)

In [4]:
print(cat0)
print(cat0.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])


In [5]:
print(cat1)
print(cat1.size())

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])
torch.Size([2, 6])


In [6]:
x = torch.zeros(2, 3)
y = torch.ones(2, 4)

In [7]:
cat1 = torch.cat((x, y), dim=1)

print(cat1)
print(cat1.size())

tensor([[0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1.]])
torch.Size([2, 7])


In [8]:
cat0 = torch.cat((x, y), dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 4 for tensor number 1 in the list.

In [9]:
x = torch.zeros(2, 3)
y = torch.ones(2, 3)

In [10]:
stack_result = torch.stack([x, y], dim=0)
cat_result = torch.cat([x, y], dim=0)

In [11]:
print(stack_result.size())
print(stack_result, '\n')

print(cat_result.size())
print(cat_result)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

torch.Size([4, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
stack_result_dim2 = torch.stack([x, y], dim=2)

print(stack_result_dim2.size())
print(stack_result_dim2)

torch.Size([2, 3, 2])
tensor([[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]])


In [13]:
x = torch.zeros(2, 3)
y = torch.ones(2, 4)

torch.stack([x, y], dim=1)

RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [2, 4] at entry 1

In [14]:
tensor = torch.tensor([1, 2])
print(tensor.device)  # cpu

cpu


In [15]:
torch.cuda.is_available()

False