<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_04_%ED%85%90%EC%84%9C%EC%9D%98_%ED%98%95%ED%83%9C_%EB%B0%94%EA%BE%B8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.randn(3, 4)
x

tensor([[-0.5767,  1.8798, -1.3621,  0.7513],
        [-1.3306,  0.6120, -1.7255,  0.1966],
        [-2.1014, -1.1148,  0.6643, -1.9267]])

In [ ]:
res0 = x.reshape(2, 6)
res0

tensor([[-0.5767,  1.8798, -1.3621,  0.7513, -1.3306,  0.6120],
        [-1.7255,  0.1966, -2.1014, -1.1148,  0.6643, -1.9267]])

In [ ]:
x.reshape(2, 5)

RuntimeError: shape '[2, 5]' is invalid for input of size 12

In [ ]:
res1 = x.reshape(-1, 2, 3)
res1.size()

torch.Size([2, 2, 3])

In [ ]:
x.reshape(-1)

tensor([-0.5767,  1.8798, -1.3621,  0.7513, -1.3306,  0.6120, -1.7255,  0.1966,
        -2.1014, -1.1148,  0.6643, -1.9267])

In [ ]:
x = torch.randn(2, 3, 4)
permuted = x.permute(2, 0, 1)

In [ ]:
permuted.size()

torch.Size([4, 2, 3])

In [ ]:
x = torch.randn(1, 28, 1, 28)

In [ ]:
result0 = x.squeeze()
result0.size()

torch.Size([28, 28])

In [ ]:
result1 = x.squeeze(2)
result1.size()

torch.Size([1, 28, 28])

In [ ]:
x = torch.randn(28, 28)

In [ ]:
result0 = x.unsqueeze(0)
result0.size()

torch.Size([1, 28, 28])

In [ ]:
result1 = x.unsqueeze(1)
result1.size()

torch.Size([28, 1, 28])