<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_02_%ED%85%90%EC%84%9C%EC%9D%98_%EB%B3%80%ED%99%98%EA%B3%BC_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
tensor = torch.ones(2, 2)

In [ ]:
np_array = tensor.numpy()
np_array

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
np_array2 = np.array(tensor)
np_array2

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
tensor[0, 0] = -1

In [ ]:
print(f'numpy() result\n{np_array}\n')
print(f'np.array() result\n{np_array2}')

numpy() result
[[-1.  1.]
 [ 1.  1.]]

np.array() result
[[1. 1.]
 [1. 1.]]


In [ ]:
a = torch.tensor([[1, 2],
                  [3, 4]])
b = torch.tensor([[1, 1],
                  [2, 2]])

In [ ]:
a + b

tensor([[2, 3],
        [5, 6]])

In [ ]:
torch.add(a, b)

tensor([[2, 3],
        [5, 6]])

In [ ]:
a * b

tensor([[1, 2],
        [6, 8]])

In [ ]:
torch.multiply(a, b)

tensor([[1, 2],
        [6, 8]])

In [ ]:
a = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
    ]
)
b = torch.tensor(
    [
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 0],
    ]
)

print(f'a의 열 개수: {a.shape[1]}')
print(f'b의 행 개수: {b.shape[0]}')

a의 열 개수: 2
b의 행 개수: 3


In [ ]:
torch.matmul(a, b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x2 and 3x3)

In [ ]:
a = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
    ]
)
b = torch.tensor(
    [
        [1, 0, 0],
        [0, 0, 1],
    ]
)

print(f'a의 열 개수: {a.shape[1]}')
print(f'b의 행 개수: {b.shape[0]}')

a의 열 개수: 2
b의 행 개수: 2


In [ ]:
torch.matmul(a, b)

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [ ]:
a @ b

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [ ]:
tensor_int = torch.tensor([1, 2], dtype=torch.int32)
tensor_float = torch.tensor([3, 4], dtype=torch.float32)

add_result = tensor_int + tensor_float
mul_result = tensor_int * tensor_float

print(add_result)
print(mul_result)

tensor([4., 6.])
tensor([3., 8.])


In [ ]:
print(add_result.dtype)
print(mul_result.dtype)

torch.float32
torch.float32


In [ ]:
tensor_int = torch.tensor([1, 2], dtype=torch.int32)
tensor_float = torch.tensor(
    [
        [3, 1],
        [1, 4]
    ],
    dtype=torch.float32
)

torch.matmul(tensor_int, tensor_float)

RuntimeError: expected m1 and m2 to have the same dtype, but got: int != float

In [ ]:
tensor_cast = tensor_int.to(torch.float32)

torch.matmul(tensor_cast, tensor_float)

tensor([5., 9.])

In [ ]:
tensor = torch.tensor([3, 5, 7, 9, 10])

In [ ]:
tensor[0]

tensor(3)

In [ ]:
tensor[2]

tensor(7)

In [ ]:
tensor[-1]

tensor(10)

In [ ]:
tensor[::2]

tensor([ 3,  7, 10])

In [ ]:
tensor_2d = torch.tensor(
    [
        [1, 3, 5, 7, 9],
        [2, 4, 6, 8, 10],
    ]
)

In [ ]:
tensor_2d[0, :3]

tensor([1, 3, 5])

In [ ]:
tensor_2d[0, 3:]

tensor([7, 9])

In [ ]:
tensor_2d[:, 1:4]

tensor([[3, 5, 7],
        [4, 6, 8]])