<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_01_%ED%85%90%EC%84%9C_%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
data_list = [1, 2]

tensor = torch.tensor(data_list)
tensor

tensor([1, 2])

In [3]:
type(tensor)

torch.Tensor

In [4]:
print(f'data type: {tensor.dtype}')
print(f'number of dimensions: {tensor.ndim}')
print(f'shape: {tensor.shape}')

data type: torch.int64
number of dimensions: 1
shape: torch.Size([2])


In [5]:
print(f'size: {tensor.size()}')

size: torch.Size([2])


In [6]:
import numpy as np

data_np = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

tensor_np = torch.tensor(data_np)
tensor_np

tensor([[1, 2],
        [3, 4]])

In [7]:
tensor_from_numpy = torch.from_numpy(data_np)
tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

In [8]:
data_np[0, 0] = -1

print(f'torch.tensor() result\n{tensor_np}\n')
print(f'torch.from_numpy() result\n{tensor_from_numpy}')

torch.tensor() result
tensor([[1, 2],
        [3, 4]])

torch.from_numpy() result
tensor([[-1,  2],
        [ 3,  4]])


In [9]:
print(tensor.dtype)
print(tensor_np.dtype)

torch.int64
torch.int64


In [10]:
tensor = torch.tensor([1, 1.5])
tensor.dtype

torch.float32

In [11]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor.dtype

torch.float32