<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_03_%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [3]:
a + b

tensor([[2, 1, 5],
        [5, 4, 8]])

In [4]:
b_expanded = torch.tensor(
    [
        [1, -1, 2],
        [1, -1, 2],
    ]
)
a + b_expanded

tensor([[2, 1, 5],
        [5, 4, 8]])

In [5]:
a = torch.tensor(
    [
        [-1, 1],
        [1, 1],
    ]
)

In [6]:
a + 1

tensor([[0, 2],
        [2, 2]])

In [7]:
a * 2

tensor([[-2,  2],
        [ 2,  2]])

In [8]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [9]:
b_expanded = torch.tensor(
    [
        [1, -1, 2],
        [1, -1, 2],
    ]
)
print(b_expanded.shape)

torch.Size([2, 3])


In [10]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([2])


In [13]:
import numpy as np
import torch

tensor0 = torch.tensor(
    [
        [1, 1], 
        [-1, -1]
    ]
)
tensor1 = torch.tensor(
    [
        [1, 1], 
        [0, 0]
    ]
)
tensor2 = torch.tensor(
    [
        [1, -1], 
        [1, -1]
    ]
)

# 여기에 코드를 작성하세요.
tensor3 = tensor0 + tensor1
tensor3 = tensor3 @ tensor2
f_tensor = tensor3 + torch.tensor([[2,-2]])
final_np_array = f_tensor.numpy()
# 테스트 코드
print(final_np_array)

[[ 6 -6]
 [ 0  0]]
