<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_03_%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [ ]:
a + b

tensor([[2, 1, 5],
        [5, 4, 8]])

In [ ]:
b_expanded = torch.tensor(
    [
        [1, -1, 2],
        [1, -1, 2],
    ]
)
a + b_expanded

tensor([[2, 1, 5],
        [5, 4, 8]])

In [ ]:
a = torch.tensor(
    [
        [-1, 1],
        [1, 1],
    ]
)

In [ ]:
a + 1

tensor([[0, 2],
        [2, 2]])

In [ ]:
a * 2

tensor([[-2,  2],
        [ 2,  2]])

In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [ ]:
b_expanded = torch.tensor(
    [
        [1, -1, 2],
        [1, -1, 2],
    ]
)
print(b_expanded.shape)

torch.Size([2, 3])


In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([2])


In [ ]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1