<a href="https://colab.research.google.com/github/Dkor-1/myTorch/blob/main/02_04_%ED%85%90%EC%84%9C%EC%9D%98_%ED%98%95%ED%83%9C_%EB%B0%94%EA%BE%B8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch
import numpy as np

In [18]:
x = torch.randn(3, 4)
x

tensor([[ 0.2931, -1.7789,  0.3168,  1.0939],
        [-0.5685,  0.2795,  0.1456,  0.2851],
        [-0.8270,  0.9450,  0.5764,  0.0865]])

In [19]:
res0 = x.reshape(2, 6)
res0

tensor([[ 0.2931, -1.7789,  0.3168,  1.0939, -0.5685,  0.2795],
        [ 0.1456,  0.2851, -0.8270,  0.9450,  0.5764,  0.0865]])

In [20]:
x.reshape(2, 5)

RuntimeError: shape '[2, 5]' is invalid for input of size 12

In [21]:
res1 = x.reshape(-1, 2, 3)
res1.size()

torch.Size([2, 2, 3])

In [22]:
x.reshape(-1)

tensor([ 0.2931, -1.7789,  0.3168,  1.0939, -0.5685,  0.2795,  0.1456,  0.2851,
        -0.8270,  0.9450,  0.5764,  0.0865])

In [25]:
x = torch.tensor(np.arange(1,25)).reshape(2,3,4)
print(x)
print("\n\n\n\n\n")
permuted = x.permute(2, 0, 1)
print(permuted)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])






tensor([[[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]],

        [[ 4,  8, 12],
         [16, 20, 24]]])


In [ ]:
permuted.size()

torch.Size([4, 2, 3])

In [ ]:
x = torch.randn(1, 28, 1, 28)

In [ ]:
result0 = x.squeeze()
result0.size()

torch.Size([28, 28])

In [ ]:
result1 = x.squeeze(2)
result1.size()

torch.Size([1, 28, 28])

In [ ]:
x = torch.randn(28, 28)

In [ ]:
result0 = x.unsqueeze(0)
result0.size()

torch.Size([1, 28, 28])

In [ ]:
result1 = x.unsqueeze(1)
result1.size()

torch.Size([28, 1, 28])