In [ ]:
import numpy as np

def prediction(theta_0, theta_1, x):
    """주어진 학습 데이터 벡터 x에 대해서 모든 예측 값을 벡터로 리턴하는 함수"""
    # 지난 실습의 코드를 여기에 붙여 넣으세요
    return theta_0 + theta_1 * x
    
def prediction_difference(theta_0, theta_1, x, y):
    """모든 예측 값들과 목표 변수들의 오차를 벡터로 리턴해주는 함수"""
    # 지난 실습의 코드를 여기에 붙여 넣으세요
    return prediction(theta_0, theta_1, x) -  y
    
def gradient_descent(theta_0, theta_1, x, y, iterations, alpha):
    """주어진 theta_0, theta_1 변수들을 경사 하강를 하면서 업데이트 해주는 함수"""
    for _ in range(iterations):  # 정해진 번만큼 경사 하강을 한다
        error = prediction_difference(theta_0, theta_1, x, y)  # 예측값들과 입력 변수들의 오차를 계산
        # 여기에 코드를 작성하세요
        theta_0 -= alpha * error.mean()
        theta_1 -= alpha * (error * x).mean()
    return theta_0, theta_1
    
    
# 입력 변수(집 크기) 초기화 (모든 집 평수 데이터를 1/10 크기로 줄임)
house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])

# 목표 변수(집 가격) 초기화 (모든 집 값 데이터를 1/10 크기로 줄임)
house_price = np.array([0.3, 0.75, 0.45, 1.1, 1.45, 0.9, 1.8, 0.9, 1.5, 2.2, 1.75, 2.3, 2.49, 2.6])

# theta 값들 초기화 (아무 값이나 시작함)
theta_0 = 2.5
theta_1 = 0

# 학습률 0.1로 200번 경사 하강
theta_0, theta_1 = gradient_descent(theta_0, theta_1, house_size, house_price, 200, 0.1)

theta_0, theta_1
    

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from math import sqrt

boston_df = pd.read_csv('boston.csv')

y = boston_df['MEDV']
X = boston_df.drop('MEDV',axis=1)

x = pd.DataFrame(X['AGE'])

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=5)

model = LinearRegression()

model.fit(x_train, y_train)

y_test_prediction = model.predict(x_test)

sqrt(mean_squared_error(y_test , y_test_prediction))

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from math import sqrt

boston_df = pd.read_csv('boston.csv')

y = boston_df['MEDV']
X = boston_df.drop('MEDV',axis=1)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=5)

model = LinearRegression()

model.fit(X_train, y_train)

y_test_prediction = model.predict(X_test)

sqrt(mean_squared_error(y_test , y_test_prediction))

In [5]:
import numpy as np

def prediction(X, theta):
    """다중 선형 회귀 가정 함수. 모든 데이터에 대한 예측 값을 numpy 배열로 리턴한다"""
    # 지난 실습의 코드를 여기에 붙여 넣으세요
    return X @ theta

def gradient_descent(X, theta, y, iterations, alpha):
    """다중 선형 회귀 경사 하강법을 구현한 함수"""
    m = len(X)  # 입력 변수 개수 저장
    
    for _ in range(iterations):
        # 여기에 코드를 작성하세요
        error = prediction(X, theta) - y

        gradient = (X.T @ error) / m

        theta = theta - alpha * gradient
        
    return theta
    

# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 목표 변수
house_price = np.array([3, 3.2, 3.6 , 8, 3.4, 4.5, 5, 5.8, 6, 6.5, 9, 9, 10, 12, 13, 15])  # 집 가격

# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 목표 변수 y 정의
y = house_price

# 파라미터 theta 초기화
theta = np.array([0, 0, 0, 0])

# 학습률 0.01로 100번 경사 하강
theta = gradient_descent(X, theta, y, 100, 0.01)

theta

array([0.11484521, 1.21120425, 0.18270523, 0.30060782])

In [6]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd  

# 당뇨병 데이터 갖고 오기
diabetes_dataset = datasets.load_diabetes()

# 입력 변수를 사용하기 편하게 pandas dataframe으로 변환
X = pd.DataFrame(diabetes_dataset.data, columns=diabetes_dataset.feature_names)

# 목표 변수를 사용하기 편하게 pandas dataframe으로 변환
y = pd.DataFrame(diabetes_dataset.target, columns=['diabetes'])

# 여기에 코드를 작성하세요

# 평균 제곱 오차의 루트를 통해서 테스트 데이터에서의 모델 성능 판단
# mse = mean_squared_error(y_test, y_test_predict)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=5)

model = LinearRegression()

model.fit(X_train, y_train)

y_test_prediction = model.predict(X_test)

sqrt(mean_squared_error(y_test , y_test_prediction))

# mse ** 0.5

54.603912902946895

In [21]:
from sklearn.preprocessing import PolynomialFeatures

boston_df = pd.read_csv('boston.csv')


y = pd.DataFrame(boston_df['MEDV'])
X = boston_df.drop('MEDV', axis=1)

polynomial_transformer = PolynomialFeatures(2)
poly_data = polynomial_transformer.fit_transform(X)
poly_feature_name = polynomial_transformer.get_feature_names_out(X.columns)
X = pd.DataFrame(poly_data, columns=poly_feature_name)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=5)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

sqrt(mean_squared_error(y_test, y_pred))

3.1965276512168455

In [29]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd  

diabetes_dataset = datasets.load_diabetes()  # 데이터 셋 갖고오기

# 여기에 코드를 작성하세요
polynomial_transformer = PolynomialFeatures(2)
polynomial_features = polynomial_transformer.fit_transform(diabetes_dataset.data)
features = polynomial_transformer.get_feature_names_out(diabetes_dataset.feature_names) 
X = pd.DataFrame(polynomial_features, columns=features)

# 테스트 코드
X.head()

1       age       sex       bmi        bp        s1        s2        s3  \
0  1.0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1  1.0 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  1.0  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3  1.0 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  1.0  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5  ...      s3^2     s3 s4     s3 s5     s3 s6      s4^2  \
0 -0.002592  0.019907  ...  0.001884  0.000113 -0.000864  0.000766  0.000007   
1 -0.039493 -0.068332  ...  0.005537 -0.002939 -0.005085 -0.006861  0.001560   
2 -0.002592  0.002861  ...  0.001047  0.000084 -0.000093  0.000839  0.000007   
3  0.034309  0.022688  ...  0.001299 -0.001236 -0.000818  0.000337  0.001177   
4 -0.002592 -0.031988  ...  0.000066 -0.000021 -0.000260 -0.000380  0.000007   

      s4 s5     s4 s6      s5^2     s5 s6      s6^2  
0 -0.000052  0.000046  0.000396 -0.000351  0.000311  
1  0.002699  0.003641  0.004669  0.006300  0.008502  
2 -0.000007  0.000067  0.000008 -0.000074  0.000672  
3  0.000778 -0.000321  0.000515 -0.000212  0.000088  
4  0.000083  0.000121  0.001023  0.001492  0.002175  

[5 rows x 66 columns]

In [3]:
import numpy as np

def sigmoid(x):
    """시그모이드 함수"""
    return 1 / (1 + np.exp(-x))
    
    
def prediction(X, theta):
    """로지스틱 회귀 가정 함수"""
    # 지난 실습의 코드를 여기에 붙여 넣으세요
    return sigmoid(X @ theta)

def gradient_descent(X, theta, y, iterations, alpha):
    """로지스틱 회귀 경사 하강 알고리즘"""
    m = len(X)  # 입력 변수 개수 저장

    for _ in range(iterations):
        # 여기에 코드를 작성하세요
        error = prediction(X, theta) - y
        theta = theta - (alpha * (X.T @ error))/len(X)
            
    return theta
    
    
# 입력 변수
hours_studied = np.array([0.2, 0.3, 0.7, 1, 1.3, 1.8, 2, 2.1, 2.2, 3, 4, 4.2, 4, 4.7, 5.0, 5.9])  # 공부 시간 (단위: 100시간)
gpa_rank = np.array([0.9, 0.95, 0.8, 0.82, 0.7, 0.6, 0.55, 0.67, 0.4, 0.3, 0.2, 0.2, 0.15, 0.18, 0.15, 0.05]) # 학년 내신 (백분률)
number_of_tries = np.array([1, 2, 2, 2, 4, 2, 2, 2, 3, 3, 3, 3, 2, 4, 1, 2])  # 시험 응시 횟수

# 목표 변수
passed = np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])  # 시험 통과 여부 (0: 탈락, 1:통과)

# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    hours_studied,
    gpa_rank,
    number_of_tries
]).T

# 목표 변수 y 정의
y = passed

theta = [0, 0, 0, 0]  # 파라미터 초기값 설정
theta = gradient_descent(X, theta, y, 300, 0.1)  # 경사 하강법을 사용해서 최적의 파라미터를 찾는다
theta

array([-1.35280508,  1.61640725, -1.83666046, -0.60286277])

In [12]:
from sklearn.datasets import load_iris
from sklearn import datasets
from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

import pandas as pd  

iris_data = load_iris()

print(iris_data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [13]:
X = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
y = pd.DataFrame(iris_data.target, columns=['class'])
# X.head()
y.head()

class
0      0
1      0
2      0
3      0
4      0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=5)

y_train = y_train.values.ravel()

In [15]:
model = LogisticRegression(solver='saga', max_iter=2000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=2000, solver='saga')

In [17]:
y_test_predict = model.predict(X_test)

In [18]:
model.score(X_test, y_test)

0.9666666666666667

In [20]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import pandas as pd  

wine_data = datasets.load_wine()
""" 데이터 셋을 살펴보는 코드
print(wine_data.DESCR)
"""

# 입력 변수를 사용하기 편하게 pandas dataframe으로 변환
X = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

# 목표 변수를 사용하기 편하게 pandas dataframe으로 변환
y = pd.DataFrame(wine_data.target, columns=['class'])

# 여기에 코드를 작성하세요
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=5)

y_train = y_train.values.ravel()

logistic_model = LogisticRegression(solver='saga', max_iter=7500)

logistic_model.fit(X_train, y_train)
y_test_predict = logistic_model.predict(X_test)

# 테스트 코드
score = logistic_model.score(X_test, y_test)
y_test_predict, score

(array([0, 1, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2]),
 0.75)